version: '3.7'
services:
  app1:
    restart: always
    build: .
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3000
      API_PORT: 3011
    ports:
      - "3011:3011"

  app2:
    restart: always
    build: .
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3000
      API_PORT: 3012
    ports:
      - "3012:3012"

  app3:
    restart: always
    build: .
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3000
      API_PORT: 3013
    ports:
      - "3013:3013"

  app4:
    restart: always
    build: .
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3000
      API_PORT: 3014
    ports:
      - "3014:3014"

  app5:
    restart: always
    build: .
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3000
      API_PORT: 3015
    ports:
      - "3015:3015"

  nginx:
    restart: always
    image: nginx
    networks:
      - visao
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  visao:
    driver: bridge